### ISSUE TITLE
Menu Bar design

### ISSUE THREAD

**Issue by orvi2014** [oa07/quizapp#8]
Design menu bar in react-native and create aboutus modal.

**Comment by sifatul** [comment]
I am taking this~

**Comment by orvi2014** [comment]
Cool. I am assigning you to this issue.

**Comment by orvi2014** [comment]
> 
> 
> I am taking this~

You are not under any team so that I can not assigning you. Can you please check the invitation link?

**Comment by orvi2014** [comment]
@Sifatul  here's the reference for you. I create a branch name menubar. you may pull it.

https://reactnavigation.org/docs/en/drawer-navigator.html

**Comment by sifatul** [comment]
i saw this ref but use korte pari na... DrawerNavigatorConfig kaj kore nai thik moto. ookay giving it a try again!

**Comment by orvi2014** [comment]
Okay try once again. if you failed, I will assign myself to this.
